llm:
  - provider: "openai"
    model: "gpt-4o-mini"
    api_key: "sk-xxx"  # 替换为你的API密钥

# 内存优化实验配置
experiment:
  name: "hurricane_mobility_memory_optimized"
  description: "Memory optimized hurricane mobility test for 16GB systems"
  
# 内存优化设置
memory_optimization:
  # 限制智能体数量以减少内存使用
  max_agents: 10  # 从100个减少到10个
  batch_size: 5   # 批处理大小

# 数据集配置
dataset:
  path: ".agentsociety-benchmark/datasets/HurricaneMobility_Small"
  
# 智能体配置
agents:
  max_count: 10  # 最大智能体数量
  
# Ray配置优化
ray_config:
  # 限制Ray使用的内存
  object_store_memory: 2000000000  # 2GB
  num_cpus: 4  # 限制CPU使用
  
# 日志配置
logging:
  level: "WARNING"  # 减少日志输出
  file: "logs/memory_optimized_benchmark.log"